### ISSUE TITLE
Question about using Kfolds with flow_from_directory

### ISSUE THREAD

**Issue by Sicily-F** [SadmanSakib93/Stratified-k-fold-cross-validation-Image-classification-keras#1]
hi there! Great code - this is so useful and thank you so much for sharing it- can I just ask - I don't quite understand which part of your code the splits occur, because you still use the training path argument in the generator. Any advice would be great - I have a data in a similar folder structure, train, val and test folders with a folder per class

thanks!

**Comment by SadmanSakib93** [comment]
Hello, thanks for the feedback. I would be glad if it helps somehow.
The **train-test split** occurs in the **line number 66** (using the custom-defined transferAllClassBetweenFolders function)
And the **validation split** happens in **line number 167**
