### ISSUE TITLE
Voting Ensemble

### ISSUE THREAD

**Issue by diniebalqis** [SadmanSakib93/Stratified-k-fold-cross-validation-Image-classification-keras#6]
Dear Sir,

May you help me to figure out the representation of X_train, Y_train, X_test, Y_test from this code? 

From my observation the representation of this four are ; 
X_train refer to train_generator,
Y_train refer to true_classes,
X_test refer to test_generator,
Y_test refer to true_classes.

And could ensemble voting be applied in this code if using VGG16 and InceptionV3? Hope you can help me figure out this problem. Thank you.

**Comment by SadmanSakib93** [comment]
Please refer to this sample repo for Ensemble (soft-voting) DL models with stratified cross-validation.
[https://github.com/SadmanSakib93/Stratified-k-fold-Cross-Validation-Ensemble-Deep-Learning-Image-Classification-Keras](url)
